### ISSUE TITLE
Expires

### ISSUE THREAD

**Issue by mizutechvoip** [Daplie/localhost.daplie.com-certificates#2]
The certificate will expire tomorrow (June 11, 2016).
Please extend it.

**Comment by coolaj86** [comment]
Thanks for the reminder.

Published as `v1.2.0`

**Comment by mizutechvoip** [comment]
So these are new certificates and we need to send out new apps with this bundled?
I am asking because we sent out some app used in production with this certificate. Will this stop to work from tomorrow?
I was thinking that you will just extend the life of the old certificate instead of creating a new one….
If you are creating a new certificate each year, then this is no suitable for more serous use as these upgrades breaks all applications.
Please confirm or deny my worries.

**Comment by coolaj86** [comment]
Certificates are signed with a date embedded in the certificate and the inexpensive certificate authorities generally sign for only 1 year.

If I were to pay several hundred dollars I might be able to get a certificate that lasts for 3 or 5 or 10 years, but even the authorities rotate or invalidate their certificates in that timeframe.

**Comment by mizutechvoip** [comment]
Ok, I understand.
