### ISSUE TITLE
does it remove SSL certificate warnings for local dev environments?

### ISSUE THREAD

**Issue by siddo420** [Daplie/localhost.daplie.com-certificates#3]
I am trying to test push notifications (service workers etc) on a local dev machine. 

But, I keep getting "ServiceWorker registration DOMException: Failed to register a ServiceWorker: An SSL certificate error occurred when fetching the script" errors. I am using a self-signed certificate on localhost.

Will your module help resolve this issue on localhost?

**Comment by coolaj86** [comment]
Yep, that's exactly what it's designed for.

`npm install -g serve-https` is the fastest way to start using it if you just need a static file server.
